---
title: "Conclusion"
---


## Conclusion
The ANOVA shows us that there is no significant difference for gender when we look at average cheating across all three conditions (Control, High cheat and Low cheat). However, when we ran the Wilcoxon ranked sum test by each condition separately, we find an interesting result in the high cheat condition. We see that there is a significant difference in gender with males cheating significantly more than females. There was no significant difference in the other two conditions. Thus we find partial evidence supporting hypothesis 1. 
To test hypothesis 2, we ran a test to check if there is a difference in the magnitude of cheating between both genders. Thus, we fail to reject the null hypothesis.

###Potential Explanations 
The most interesting result in this study was that men cheat more than women in the high cheat condition, but not in the low cheat or control condition. One potential explanation for this could be that social desirability bias plays an important role with men in the high cheat condition. When stakes are higher, they might feel the need to achieve more and in this case, the group performance and subsequent reward is affected by higher scores. 
We find no difference in the magnitude of cheating by gender and this could be explained by the fact that the incentive to cheat was not strong enough in our experiment.

###Implications
The potential implications of this result could be that women should be placed in roles that have high stakes as they seem to be less tempted to cheat at the thought of higher gains with more cheating. However, since this study does not look at the gender of the leader, further analysis is required before we can draw any definitive conclusions.


##Work Cited

Amini, M., Ekström, M., Ellingsen, T., Johannesson, M., & Strömsten, F. (2016). Does gender diversity promote nonconformity?. Management Science, 63(4), 1085-1096.

Betz, M., O'Connell, L., & Shepard, J. M. (1989). Gender differences in proclivity for unethical behavior. Journal of Business Ethics, 8(5), 321-324.

d’Adda, G., Darai, D., Pavanini, N., & Weber, R. A. (2017). Do leaders affect ethical conduct?. Journal of the European Economic Association, 15(6), 1177-1213.

Dalton, D., & Ortegren, M. (2011). Gender differences in ethics research: The importance of controlling for the social desirability response bias. Journal of Business Ethics, 103(1), 73-93.

Gächter, S., & Renner, E. (2017). Leaders as role models and ‘belief managers’ in social dilemmas. Journal of Economic behavior & Organization, 154, 321-334.






