---
title: "Introduction"
---

## Introduction
### Motivation

The motivation for my project stems from my interest in leadership influence and how unethical behaviour by leaders can motivate unethical follower behaviour. In this project, I am specifically interested in observing the effect the gender of followers has on their actions.

This project is an extension of my BDS 501 group project "When Leaders Cheat" where we wanted to test the impact of leaders taking actions themselves on the ethical conduct of their followers. The study focuses on examining the potential diffusion of unethical behaviour (and the extent of this diffusion) from unethical leaders to followers when followers are able to directly observe the behaviour of unethical leaders. 

Behaviors are contagious. From quitting smoking to divorce, researchers have found that we are more likely to adopt the behaviors that we see others engaging in (McDermott, Fowler & Christakis, 2009). In the wake of recent corporate scandals, scholars and practitioners have become increasingly convinced that such a behavioral contagion effect exists in the context of ethics and leadership as well (Trevino, Brown & Hartman, 2003): to a large degree, employees tend to calibrate their behavior according to their leader’s actions (“When something is rotten”, 2002). Despite this general consensus, the relationship between leader behavior and (un)ethical conduct among followers has only recently been examined experimentally and is still not fully understood (d’Adda et al., 2017). 

The relationship between unethical leaders and followers has been observed repeatedly in a real world in every sphere be it in an academic, industry or political context. Famous examples of unethical conduct in the corporate sector include the Enron scandal of 2001, WorldCom scandal of 2002, and the Wells Fargo scandal of 2017. While numerous examples exist in politics, one prominent one is the Watergate scandal of 1972 and a famous example in academia is Diederik Stapel of University of Tilburg whose falsified research compromised all further work that relied on his results. A common factor in all these examples is the fact that the person in a leadership role was male, prompting the question - would having a larger representation of women in organisations affect ethical behaviour?

### Prior Literature
Looking at the literature on the broader topic of unethical leaders, d'Adda et al. focused on studying if leaders influence the unethical conduct of followers (2017). In their paper, leaders communicate unethical expectations through public announcements and incentives. Gächter & Renner find in their paper that a leader's actions may strongly influence the initial beliefs and contributions of followers' contributions to a public goods game but do little to shift follower behaviour later (2017).

Specifically for this project, since I am interested in the gender of followers, we look at prior literature about gender in relation to unethical behaviour. One study shows that men are more likely to engage in unethical behaviour compared to females in relation to buying stocks with insider information (Betz, O'Connell and Shephard 1989). While in contrast to that, Amini et al. finds that gender composition has little effect on conformity levels (2016). Dalton and Ortegren found that the effect of gender differences on ethical leadership is affected by the social desirability bias (2011). It would be interesting to see whether the gender of the followers has an effect on cheating behaviour as well as the magnitude of cheating. 

## Hypotheses

My research hypotheses are as follows:

$H_0$: There is no difference in follower behaviour based on the gender 

$H_1$: Male followers are more likely to cheat than female followers

$H_2$: The magnitude of cheating by male followers is more than female followers
